# =============================================================================
# Aggregator overlay for the prod cluster.
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../shared
  - ../../controller.yaml
  - dind
  - kubernetes-pvc
  - kubernetes-novolume
