# =============================================================================
# Per-runner-type overlay (dev / dind / community flavor)
# =============================================================================
# Final name: straw-hat-runners-linux-dev-dind
# =============================================================================
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/community
nameSuffix: -dev-dind
patches:
  - patch: |
      - op: replace
        path: /metadata/name
        value: "straw-hat-runners-linux-dev-dind"
      - op: replace
        path: /spec/template/spec/group
        value: "straw-hat-runners-linux-dev-dind"
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/image
        value: "ghcr.io/strawhat-enterprise/actions-runner:linux-dind-latest"
    target:
      kind: RunnerDeployment
      name: runner-deployment
